# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IBuyOff' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IBuyOff
 
  

  target 'IBuyOffTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IBuyOffUITests' do
    # Pods for testing
  end

end
